const path = require("path");
const fs = require("fs");
const os = require("os");

let configPath = "";
let dataDir = "";
let config = {};

// Detect if running inside a packaged pkg environment
const isPackaged = typeof process.pkg !== "undefined";

function generateConfigContent(detected) {
  const formatValue = (val) => {
    if (Array.isArray(val)) {
      return "[\n" + val.map((p) => `        ${JSON.stringify(p)}`).join(",\n") + "\n    ]";
    }
    return JSON.stringify(val);
  };

  return `// ============================================================================
// MEM0RAY CONFIGURATION CONTRACT
// ============================================================================
// This configuration was auto-generated by the Mem0Ray setup detector.
// You can edit these paths below, or configure them using the Mission Control dashboard.
// ============================================================================

module.exports = {
    // Directory where Claude Code stores active session PIDs
    CLAUDE_SESSIONS_DIR: ${formatValue(detected.CLAUDE_SESSIONS_DIR.value)},

    // Directories where Claude Code stores conversational logs (.jsonl)
    CLAUDE_LOG_DIRS: ${formatValue(detected.CLAUDE_LOG_DIRS.value)},

    // Path to the file that tracks Git Worktrees created by Claude Code
    CLAUDE_WORKTREES_PATH: ${formatValue(detected.CLAUDE_WORKTREES_PATH.value)},

    // Path to the Claude Desktop application configuration (for tool discovery)
    CLAUDE_CONFIG_PATH: ${formatValue(detected.CLAUDE_CONFIG_PATH.value)},

    // Directories where Antigravity stores its conversation trajectories (.jsonl)
    ANTIGRAVITY_BRAIN_DIRS: ${formatValue(detected.ANTIGRAVITY_BRAIN_DIRS.value)},

    // Directory for Gemini Agent plugins and core configuration
    GEMINI_CONFIG_DIR: ${formatValue(detected.GEMINI_CONFIG_DIR.value)},

    // Directories where opencode stores its session/message/part JSON tree
    OPENCODE_STORAGE_DIRS: ${formatValue(detected.OPENCODE_STORAGE_DIRS.value)},

    // Path to the opencode config (providers, models, MCP servers, permissions)
    OPENCODE_CONFIG_PATH: ${formatValue(detected.OPENCODE_CONFIG_PATH.value)},

    // Base URL of the open-notebook FastAPI REST API (docker-compose default)
    OPEN_NOTEBOOK_API_URL: "http://localhost:5055"
};
`;
}

// Configuration and database always live in the user's home folder (~/.mem0ray)
const configDir = path.join(os.homedir(), ".mem0ray");
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir, { recursive: true });
}

configPath = path.join(configDir, "mem0ray.config.js");
dataDir = path.join(configDir, "data");

// If config file doesn't exist, create it dynamically using the detector
if (!fs.existsSync(configPath)) {
  try {
    const { detectPaths } = require("./detector");
    const detected = detectPaths().results;
    const configContent = generateConfigContent(detected);
    fs.writeFileSync(configPath, configContent, "utf8");
  } catch (err) {
    console.error("[Config] Failed to generate default config:", err.message);
  }
}

// Make sure the data directory exists
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const vm = require("vm");

function reloadConfig() {
  try {
    const { detectPaths } = require("./detector");
    const detected = detectPaths().results;
    const defaultConfig = {};
    for (const key of Object.keys(detected)) {
      defaultConfig[key] = detected[key].value;
    }

    let userConfig = {};
    if (fs.existsSync(configPath)) {
      const content = fs.readFileSync(configPath, "utf8");
      const sandbox = {
        module: { exports: {} },
        require: require,
        path: path,
        os: os,
        console: console
      };
      vm.runInNewContext(content, sandbox);
      userConfig = sandbox.module.exports || {};
    }

    // Mutate the existing config object in-place so references in other modules remain valid
    for (const key of Object.keys(config)) {
      delete config[key];
    }
    Object.assign(config, defaultConfig);

    for (const [key, val] of Object.entries(userConfig)) {
      if (val !== undefined && val !== null) {
        if (Array.isArray(val) && val.length === 0 && Array.isArray(defaultConfig[key]) && defaultConfig[key].length > 0) {
          continue;
        }
        if (val === "" && defaultConfig[key]) {
          continue;
        }
        config[key] = val;
      }
    }
  } catch (e) {
    console.error(`[Config] Failed to load configuration from ${configPath}:`, e.message);
  }
}

// Initial load
reloadConfig();

module.exports = {
  config,
  configPath,
  dataDir,
  isPackaged,
  reloadConfig
};
