// Book PDF: our own generated markdown → print-styled HTML → PDF via the
// system browser's headless print (Edge on Windows, Chrome fallback). No new
// dependencies: the markdown is machine-generated by this pipeline, so a
// constrained converter that handles exactly what we emit is safe.
import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function inline(s) {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}

export function mdToHtml(md, { title = "Book" } = {}) {
  const lines = md.split(/\r?\n/);
  const out = [];
  let inList = false;
  let inCode = false;
  const closeList = () => {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  };
  for (const raw of lines) {
    const line = raw;
    if (line.trim().startsWith("```")) {
      closeList();
      out.push(inCode ? "</pre>" : "<pre>");
      inCode = !inCode;
      continue;
    }
    if (inCode) {
      out.push(esc(line));
      continue;
    }
    if (/^# /.test(line)) {
      closeList();
      out.push(`<h1>${inline(line.slice(2))}</h1>`);
    } else if (/^## /.test(line)) {
      closeList();
      out.push(`<h2>${inline(line.slice(3))}</h2>`);
    } else if (/^### /.test(line)) {
      closeList();
      out.push(`<h3>${inline(line.slice(4))}</h3>`);
    } else if (/^---+\s*$/.test(line)) {
      closeList();
      out.push("<hr/>");
    } else if (/^\s*- /.test(line)) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${inline(line.replace(/^\s*- /, ""))}</li>`);
    } else if (line.trim() === "") {
      closeList();
    } else {
      closeList();
      out.push(`<p>${inline(line)}</p>`);
    }
  }
  closeList();
  if (inCode) out.push("</pre>");

  // Print CSS: book-ish serif body, chapters on fresh pages, page margins.
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
  @page { size: A4; margin: 22mm 20mm; }
  body { font-family: Georgia, 'Times New Roman', serif; font-size: 11.5pt; line-height: 1.55; color: #1a1a1a; max-width: 46em; margin: 0 auto; }
  h1 { page-break-before: always; font-size: 22pt; margin-top: 3em; }
  h1:first-of-type { page-break-before: avoid; text-align: center; margin-top: 30%; }
  h2 { page-break-before: always; font-size: 16pt; margin-top: 2.5em; }
  h3 { font-size: 12.5pt; margin-top: 1.8em; page-break-after: avoid; }
  p { orphans: 3; widows: 3; text-align: justify; }
  hr { border: none; border-top: 1px solid #999; margin: 2em 25%; }
  code { font-family: Consolas, monospace; font-size: 0.9em; background: #f2f2f2; padding: 0 3px; }
  pre { font-family: Consolas, monospace; font-size: 9pt; background: #f6f6f6; padding: 8px; white-space: pre-wrap; }
  ul { margin: 0.4em 0 0.8em 1.4em; }
</style></head><body>${out.join("\n")}</body></html>`;
}

function findBrowser() {
  const candidates = [
    "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe",
    "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
  ];
  return candidates.find((p) => fs.existsSync(p)) || null;
}

export function htmlToPdf(htmlPath, pdfPath) {
  const browser = findBrowser();
  if (!browser) {
    return { ok: false, error: "no Edge/Chrome found for headless print-to-pdf" };
  }
  const fileUrl = "file:///" + path.resolve(htmlPath).replace(/\\/g, "/");
  const r = spawnSync(
    browser,
    [
      "--headless",
      "--disable-gpu",
      `--print-to-pdf=${path.resolve(pdfPath)}`,
      "--no-pdf-header-footer",
      fileUrl
    ],
    { timeout: 300000, encoding: "utf8" }
  );
  if (fs.existsSync(pdfPath) && fs.statSync(pdfPath).size > 10000) {
    return { ok: true, browser: path.basename(browser), bytes: fs.statSync(pdfPath).size };
  }
  return { ok: false, error: (r.stderr || "print produced no output").slice(0, 300) };
}
